export const actionType = {
  REGISTER_USER: 'REGISTER_USER',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  REGISTRATION_ERROR: 'REGISTRATION_ERROR',
  RESEND_CODE: 'RESEND_CODE',
  SUBMIT_TOKEN: 'SUBMIT_TOKEN',
  VALIDATION_SUCCESS: 'VALIDATION_SUCCESS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
};
