export const actionType = {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  RECOVER_ERROR: 'RECOVER_ERROR',
  RECOVER_SUCCESS: 'RECOVER_SUCCESS',
  RECOVER: 'RECOVER',
};
